### ISSUE TITLE
Support Gnome 40

### ISSUE THREAD

**Issue by benruijl** [sereneblue/gnome-shell-extension-krypto#2]
The extension cannot be enabled in Gnome 40.

**Comment by sereneblue** [comment]
Hi @benruijl, I encountered the same issue after updating. Since GNOME 40 uses GTK 4, the current UI (built for GTK 3) fails to load. I hope to have an update out soon.

EDIT: There are some additional code changes that will be needed to get everything working again. Essentially, this looks to be a rewrite.

**Comment by sereneblue** [comment]
@benruijl v6 adds support for Gnome 40 with an updated UI and support for more currencies. I suggest manually updating following the instructions in the readme. It may take some time before the new version is approved on the extensions website.
